### PR TITLE
DFGrad II: Comment and Correct `dfmp2`

### LINKED ISSUE #1916: DF-MP2 Gradients Incorrect with Frozen Virtual
Running the following input file
```
molecule {
O
H 1 1.0
H 1 1.0 2 104.5
symmetry c1
}

set {
    scf_type      mem_df
    basis         cc-pvdz
    num_frozen_uocc 4
    mp2_type      df
}

analytic = gradient("mp2")
findif = gradient("mp2", dertype=0)

compare_matrices(analytic, findif, 4, "DF-MP2 Gradient")
```

gives me

```
  Expected:
    [[-0.              0.000000000003 -0.034538336725]
     [ 0.             -0.035340551119  0.017269168364]
     [ 0.              0.035340551116  0.017269168361]]
  Observed:
    [[ 0.              0.000000000422 -0.029704789758]
     [ 0.             -0.030742173112  0.014852395042]
     [ 0.              0.030742172689  0.014852394715]]
  Difference (passed elements are zeroed):
    [[ 0.              0.              0.004833546968]
     [ 0.              0.004598378007 -0.002416773321]
     [ 0.             -0.004598378426 -0.002416773646]]
```

So we have a third decimal place error(!) in DF-MP2 frozen virtual gradients. Frozen core gradients test fine.

@loriab, take note of this during your standardization and testing pass.

Core developers, assign this to me. If it's a simple fix, this will be part of DFGrad II. Otherwise, this will be DFGrad III. I'm also requesting, given the severity of this bug, that it be made a Psi 1.4 target.

### PR DESCRIPTION
**Pull request by JonathonMisiewicz**
## Description
This PR closes #1916 and corrects a bug causing third-decimal errors in gradients computed by `dfmp2` with the frozen virtual approximation. See the commit marked "Bugfix!" to see exactly what the issue was. There was a sign error, and Rob was looping over frozen core orbitals when he meant to loop over frozen virtual orbitals.

More importantly for me, this code inserts many, many comments into Rob's code, so I know what I'm doing when I modify it throughout the rest of this PR series. This includes uncovering a very devious computational trick, that as far as I know is unpublished, and also some errors in the original papers. Many thanks to Francesco and Shuhe for the DSRG-PT2 paper, which formed part of the Rosetta Stone for figuring out how this code works.

Several explicit types are now `auto`. Reviewers, double-check that I didn't accidentally remove a pass-by-reference or `const` declaration when doing so.

Lastly, `test_gradients.py` has been added to pytests to confirm the accuracy of `dfmp2` gradients. This PR series will culminate with the addition of DF-ODC-12 to `test_gradients.py`. Currently, DF-ODC-12 would fail due to #1579.

## Todos
Notable points (developer or user-interest) that this PR has or will accomplish.
- [x] Corrects a critical bug causing errors in frozen virtual gradients computed with the `dfmp2` module
- [x] Adds many comments to `dfmp2`
- [x] Replaces a lot of explicit type with `auto`

## Checklist
- [x] Tests added for newly working features
- [x] `dfmp2` tests pass

## Status
- [x] Ready for review
- [x] Ready for merge

### CODE REVIEW

File: psi4/src/psi4/dfmp2/mp2.cc [hunk 1]
```diff
@@ -346,67 +346,51 @@ void DFMP2::form_singles() {
     SharedVector eps_aocc_b = epsilon_b_subset("SO", "ACTIVE_OCC");
     SharedVector eps_avir_b = epsilon_b_subset("SO", "ACTIVE_VIR");
 
-    auto Fia_a = std::make_shared<Matrix>("Fia a", Caocc_a->colspi(), Cavir_a->colspi());
-    auto Fia_b = std::make_shared<Matrix>("Fia b", Caocc_b->colspi(), Cavir_b->colspi());
+    auto Fia_a = linalg::triplet(Caocc_a, Fa_, Cavir_a, true, false, false);
+    auto Fia_b = linalg::triplet(Caocc_b, Fb_, Cavir_b, true, false, false);
```
Comment (loriab) [inline psi4/src/psi4/dfmp2/mp2.cc:350]: smart `triplet`. guess the dfmp2 module was from days before the invention of `doublet` and `triplet`.
