### PR TITLE
rebased: Improve some default parameters in PK code

### LINKED ISSUE #398: Compiler error PK_workers.cc file with the Intel 14 compiler
I was trying to compile psi4 using the Intel 14 compiler and I got an error:
PK_workers.cc(755): error: no instance of constructor "psi::pk::PKWorker::PKWorker" matches the argument list
            argument types are: (boost::shared_ptr<psi::BasisSet>, psi::pk::SharedSieve, long, int, size_t)
      PKWorker(primary,sieve, NULL,0,buf_size) {
              
I changed NULL to std:shared_ptr<AIOHandler>() and it fixed the compiler error. Do you think this may have a side effect?

### PR DESCRIPTION
**Pull request by loriab**
## Description
Hopefully better code, to pass default empty vectors and pointers. By @jgonthier 

## Todos
Notable points that this PR has either accomplished or will accomplish.
- [x] fixes #398 

## Status
- [x]  Ready to go

### CODE REVIEW

File: psi4/src/psi4/libfock/PKmanagers.cc [hunk 1]
```diff
@@ -437,7 +437,7 @@ void PKManager::make_J_vec(std::vector<SharedMatrix> J) {
         // Shared pointer initialized to null
         //TODO Could actually store triangle since J is always symmetric
         } else {
-            JK_vec_.push_back(nullptr);
+            JK_vec_.push_back(NULL);
         }
```
Comment (dgasmith) [inline psi4/src/psi4/libfock/PKmanagers.cc]: Shouldnt this be `nullptr` since `JK_vec_ = std::vector<double*>`?

**Comment by jturney** [comment]
LGTM

**Comment by loriab** [comment]
LGTM

(I want to test lgtm counting)

**Comment by dgasmith** [comment]
LGTM

File: psi4/src/psi4/libfock/PKmanagers.cc (hunk 1 above)
Comment (jgonthier) [inline psi4/src/psi4/libfock/PKmanagers.cc]: Yes, you're right, strictly speaking it could be better to keep ``nullptr``. Feel free to do it since I have not updated my forks yet...
