### PR TITLE
Issue cleanup: fix various crashes.

### LINKED ISSUE #1613: Relativistic calculations referring to non-standard basis fails
This problem was already mentioned in passing here: https://github.com/psi4/psi4/issues/662#issuecomment-475861476

This is a simple example input file showing the problem:

```
molecule {
  H
}

set {
    scf_type pk
    basis ano-rcc
    relativistic x2c
    reference uhf
}

energy('hf')
```

I have set my `$PSIPATH` to a directory containing the basis set file (downloaded from EMSL):

```bash
ll $PSIPATH
total 2.1M
drwxr-xr-x. 2 toon toon 4.0K Apr 29 17:13 .
drwxr-xr-x. 7 toon toon 4.0K Apr 29 16:34 ..
-rw-r--r--. 1 toon toon 2.1M Apr 29 15:49 ano-rcc.gbs
```

When running Psi4 on this input, I get the following error message:

```
Traceback (most recent call last):
  File "/home/toon/miniconda3/envs/p4dev/bin/psi4", line 287, in <module>
    exec(content)
  File "<string>", line 26, in <module>
  File "/home/toon/miniconda3/envs/p4dev/lib/psi4/driver/driver.py", line 561, in energy
    wfn = procedures['energy'][lowername](lowername, molecule=molecule, **kwargs)
  File "/home/toon/miniconda3/envs/p4dev/lib/psi4/driver/procrouting/proc.py", line 2045, in run_scf
    scf_wfn = scf_helper(name, post_scf=False, **kwargs)
  File "/home/toon/miniconda3/envs/p4dev/lib/psi4/driver/procrouting/proc.py", line 1281, in scf_helper
    scf_wfn = scf_wavefunction_factory(name, base_wfn, core.get_option('SCF', 'REFERENCE'), **kwargs)
  File "/home/toon/miniconda3/envs/p4dev/lib/psi4/driver/procrouting/proc.py", line 1056, in scf_wavefunction_factory
    puream=wfn.basisset().has_puream())
  File "/home/toon/miniconda3/envs/p4dev/lib/psi4/driver/p4util/python_helpers.py", line 80, in _pybuild_basis
    mol.to_dict(), key, resolved_target, fitrole, other, return_dict=True, return_atomlist=return_atomlist)
  File "/home/toon/miniconda3/envs/p4dev/lib/psi4/driver/qcdb/libmintsbasisset.py", line 679, in pyconstruct
    verbose=verbose)
  File "/home/toon/miniconda3/envs/p4dev/lib/psi4/driver/qcdb/libmintsbasisset.py", line 838, in construct
    filename = cls.make_filename(basgbs)
  File "/home/toon/miniconda3/envs/p4dev/lib/psi4/driver/qcdb/libmintsbasisset.py", line 1396, in make_filename
    basisname = basisname.lower()

AttributeError: 'NoneType' object has no attribute 'lower'

Printing out the relevant lines from the Psithon --> Python processed input file:
    core.IO.set_default_namespace("")
    core.set_global_option("SCF_TYPE", "pk")
    core.set_global_option("BASIS", "ano-rcc")
    core.set_global_option("RELATIVISTIC", "x2c")
    core.set_global_option("REFERENCE", "uhf")
--> energy('hf')
```

This problem was previously also brought up on the forum: http://forum.psicode.org/t/scf-problems-please-help/765/1

### LINKED ISSUE #1675: Molecule xyz getter segfault
Currently the `Molecule.xyz()` method does not check the length of the array that it is getting.

```
>>> import psi4
>>> mol  = psi4.geometry("He 0 0 0\nHe 0 0 5")
>>> mol.xyz(3)
[1]    26521 segmentation fault  python
```

This should be capped and provide a nice error message to the user. This should be a straightforward fix, the relevant file is [here](https://github.com/psi4/psi4/blob/master/psi4/src/psi4/libmints/molecule.cc).

### LINKED ISSUE #1694: Calculations fail in unconventional basis sets
A segfaulting test case
```
molecule {
0 2
H
}
set reference uhf
set df_scf_guess false
set scf_type direct

basis {
assign test

[test]
spherical
****
H 0
P 1 1.0
 1.0 1.0
****
}
energy('scf')
```

I have found one issue and fixed it in hf.cc
```
diff --git a/psi4/src/psi4/libscf_solver/hf.cc b/psi4/src/psi4/libscf_solver/hf.cc
index fec5efaa4..c462addab 100644
--- a/psi4/src/psi4/libscf_solver/hf.cc
+++ b/psi4/src/psi4/libscf_solver/hf.cc
@@ -705,9 +705,15 @@ void HF::form_Shalf() {
 
     // Convert the eigenvales to 1/sqrt(eigenvalues)
     const Dimension& dimpi = eigval->dimpi();
-    double min_S = std::fabs(eigval->get(0, 0));
+    // Cannot assume that (0,0) is a valid reference
+    bool min_S_initialized = false;
+    double min_S;
     for (int h = 0; h < nirrep_; ++h) {
         for (int i = 0; i < dimpi[h]; ++i) {
+            if(!min_S_initialized) {
+              min_S = eigval->get(h, i);
+              min_S_initialized = true;
+            }
```
but now the code crashes somewhere in pybind11.

### PR DESCRIPTION
**Pull request by PeterKraus**
## Description
Resolves #1694 by throwing an exception when active molecule has only 1 fragment.
Resolves #1675 by throwing an exception when requested atom is out of bounds.
Resolves #1613 by changing the lookup path for AUX/DECON bases from `libraryPath` to `basisPath`.

## Checklist
- [ ] [All or relevant fraction of full tests run](http://psicode.org/psi4manual/master/build_planning.html#how-to-run-a-subset-of-tests)

## Status
- [x] Ready for review
- [x] Ready for merge

### CODE REVIEW

File: psi4/src/psi4/libmints/molecule.cc [hunk 1]
```diff
@@ -2221,47 +2221,100 @@ std::vector<std::string> Molecule::irrep_labels() {
...
 
-void Molecule::set_nuclear_charge(int atom, double newZ) { atoms_[atom]->set_nuclear_charge(newZ); }
+void Molecule::set_nuclear_charge(int atom, double newZ) {
+    if (atom >= atoms_.size()) throw std::runtime_error("Requested atom doesn't exist.");
+    atoms_[atom]->set_nuclear_charge(newZ);
+}
 
-const std::string &Molecule::basis_on_atom(int atom) const { return atoms_[atom]->basisset(); }
+const std::string &Molecule::basis_on_atom(int atom) const {
+    if (atom >= atoms_.size()) throw std::runtime_error("Requested atom doesn't exist.");
```
Comment (dgasmith) [inline psi4/src/psi4/libmints/molecule.cc]: Would it make more sense if this was a utility function `void check_atom(int atom)`?

Might make things slightly simpler.

File: psi4/driver/qcdb/libmintsbasisset.py [hunk 2]
```diff
@@ -808,7 +808,7 @@ def construct(cls, parser, mol, key, deffit=None, basstrings=None, return_atomli
                         tmp.append(univdef[deffit])
                     seek['basis'] = [item for item in tmp if item != (None, None, None)]
                     seek['entry'] = [symbol]
-                    seek['path'] = libraryPath
+                    seek['path'] = basisPath
```
Comment (dgasmith) [inline psi4/driver/qcdb/libmintsbasisset.py]: I think this right, but defiantly needs a @loriab thumbs up.

Comment (loriab) [reply psi4/driver/qcdb/libmintsbasisset.py]: When the issue came up, I couldn't decide for several days if I was comfortable with the switch. Now ok with it.

File: psi4/src/psi4/libmints/molecule.h [hunk 3]
```diff
@@ -277,6 +277,8 @@ class PSI_API Molecule {
     double xyz(int atom, int _xyz) const;
     /// Returns mass atom atom
     double mass(int atom) const;
+    /// Checks whether atom is within bounds of atom_ or full_atom_
+    void check_atom_(int atom, bool full) const;
```
Comment (loriab) [inline psi4/src/psi4/libmints/molecule.h]: By my understanding, because `check_atom_` is just a helper function local to the `.cc` file, it doesn't need to be declared in the header, and the definition in the `.cc` can drop the `Molecule::` part.

A rebase will fix Azure now, but we can also simply merge after the 3rd review since it'll heal in master.

Comment (PeterKraus) [reply psi4/src/psi4/libmints/molecule.h]: I don't think that works, as the function needs to access `atoms_` and `full_atoms_` which are only defined if the function belongs to the `Molecule::` class.

At least, with L281 commented and https://github.com/psi4/psi4/blob/7a892760e628f2d54ba02d6d09da71acf4c42c8c/psi4/src/psi4/libmints/molecule.cc#L2224 changed to:
```
void check_atom_(int atom, bool full) const  {
```

the compilation crashes with `error: 'full_atoms_' was not declared in this scope`.

Comment (loriab) [reply psi4/src/psi4/libmints/molecule.h]: Sounds about like the depth of my C++ experience. Try for `protected:`, then, like https://github.com/psi4/psi4/blob/master/psi4/src/psi4/libmints/molecule.h#L155
