### PR TITLE
Fix #2976

### LINKED ISSUE #2976: DF-MP2 does not work on lithium
The input
```
molecule {
0 2
Li
}

set basis def2-SVP
set reference uhf
set freeze_core True
set scf_type df
set mp2_type df

energy('mp2')
```
results in a crash:
```
!----------------------------------------------------------------------------------!
!                                                                                  !
! Fatal Error: There are no occupied orbitals with beta spin.                      !
! Error occurred in file: /scratch/psilocaluser/conda-                             !
!     builds/psi4-multiout_1671346910751/work/psi4/src/psi4/dfmp2/mp2.cc on line:  !
!     206                                                                          !
! The most recent 5 function calls were:                                           !
!                                                                                  !
!----------------------------------------------------------------------------------!
```
even though there are occupied orbitals with beta spin
```
         --------------------------------------------------------
                                  DF-MP2                         
              2nd-Order Density-Fitted Moller-Plesset Theory     
                      UMP2 Wavefunction,   1 Threads             
                                                                 
                Rob Parrish, Justin Turney, Andy Simmonett,      
                   Ed Hohenstein, and C. David Sherrill          
         --------------------------------------------------------

         --------------------------------------------------------
                         NBF =     9, NAUX =    25
         --------------------------------------------------------
           CLASS    FOCC     OCC    AOCC    AVIR     VIR    FVIR
           ALPHA       1       2       1       7       7       0
            BETA       1       1       0       8       8       0
         --------------------------------------------------------

```
A related issue is that the hydrogen also fails with the same error. For hydrogen (or any one-electron system), MP2 should return the HF energy.

### PR DESCRIPTION
**Pull request by JonathonMisiewicz**
## User API & Changelog headlines

- [x] Fixes a crash when attempting DFMP2 on systems with too few electrons to support MP2

## Dev notes & details

- [x] Massively simplified the DFMP2 validation logic

## Checklist
- [x] dfmp2 tests pass
- [x] Turned the bug report into a new test case. (Thanks for a clean one, Susi.)

## Status
- [x] Ready for review
- [x] Ready for merge

### CODE REVIEW

File: psi4/src/psi4/dfmp2/mp2.cc [hunk 1]
```diff
@@ -186,34 +186,16 @@ void DFMP2::common_init() {
...
-        if (Cb_subset("AO", "ACTIVE_VIR")->colspi()[0] == 0) {
-            throw PSIEXCEPTION("There are no virtual orbitals with alpha or beta spin.");
-        }
-        throw PSIEXCEPTION("There are no virtual orbitals with alpha spin.");
-    }
-    if (Cb_subset("AO", "ACTIVE_VIR")->colspi()[0] == 0) {
-        throw PSIEXCEPTION("There are no virtual orbitals with beta spin.");
+    auto num_alpha_excit = std::min(Ca_subset("AO", "ACTIVE_OCC")->colspi()[0], Ca_subset("AO", "ACTIVE_VIR")->colspi()[0]);
+    auto num_beta_excit = std::min(Cb_subset("AO", "ACTIVE_OCC")->colspi()[0], Cb_subset("AO", "ACTIVE_VIR")->colspi()[0]);
+    if (num_alpha_excit + num_beta_excit < 2) {
```
Comment (loriab) [inline psi4/src/psi4/dfmp2/mp2.cc:191]:
```suggestion
    if (num_alpha_excit + num_beta_excit < 2) {
        print_out("  Warning: no MP2 calculation performed on system with alpha ACTIVE_OCC (%d), beta ACTIVE_OCC (%d), alpha ACTIVE_VIR (%d), beta ACTIVE_VIR (%d); returning 0.0 by definition.\n", Ca_subset("AO", "ACTIVE_OCC")->colspi()[0], Cb_subset("AO", "ACTIVE_OCC")->colspi()[0], Ca_subset("AO", "ACTIVE_VIR")->colspi()[0], Cb_subset("AO", "ACTIVE_VIR")->colspi()[0]);
```

**Review by loriab — APPROVED** [review]
So of the 8 alpha/beta active_occ/_vir cases that had zero or one electrons, previously this would throw with an informative message for 7 and return 0.0 for 1 (occ 1a0b), while now it returns 0.0 for all 8? Nice logic simplification. I've suggested some extra printing in case no-op wasn't intended.

**Review by susilehtola — APPROVED** [review]

File: psi4/src/psi4/dfmp2/mp2.cc (hunk 1 above)
Comment (JonathonMisiewicz) [reply psi4/src/psi4/dfmp2/mp2.cc:191]: Implemented with minor correction and update to `output.ref`.
