### PR TITLE
Close #2712

### LINKED ISSUE #2712: SCF Gradient Segfault
Either both of the below attempts to read a wfn in for an SCF gradient should be trapped by an error, or neither should. Right now, the first works fine, but the bottom segfaults.

```
h2o = psi4.geometry("""
        O   
        H 1 0.96
        H 1 0.96 2 104.5
        """)
wfn=psi4.energy('scf/def2-svp', molecule=h2o, return_wfn=True)[1]
# No segfault with the un-serialized wfn.
psi4.gradient('scf/def2-svp', molecule=wfn.molecule(), ref_wfn=wfn)

wfn.to_file('my_wfn')
wfn_new = psi4.core.Wavefunction.from_file('my_wfn')
# Segfault with the un-serialized wfn.
psi4.gradient('scf/def2-svp', molecule=wfn_new.molecule(), ref_wfn=wfn_new) # Segfault here.
```

### PR DESCRIPTION
**Pull request by JonathonMisiewicz**
## Description

Closes #2712. Please do not use C-style casting for complicated types.

## Release Notes Delta

- [x] **Bugfix:** Seeding an SCF gradient with a ref_wfn that isn't SCF now raises an error rather than a segfault.

## Checklist
- [x] `grad` and `hess` ctests pass.

## Status
- [x] Ready for review
- [x] Ready for merge

### CODE REVIEW

File: psi4/src/psi4/scfgrad/wrapper.cc [hunk 1]
```diff
@@ -49,17 +49,17 @@ SharedMatrix scfgrad(SharedWavefunction ref_wfn, Options &options)
...
-SharedMatrix scfhess(SharedWavefunction ref_wfn, Options &options)
+SharedMatrix scfhess(std::shared_ptr<scf::HF> ref_wfn, Options &options)
 {
     tstart();
 
     SharedMatrix H;
     if( ref_wfn->same_a_b_orbs() && ref_wfn->same_a_b_dens()) {
         // RHF
-        RSCFDeriv hessian_computer(std::dynamic_pointer_cast<scf::RHF>(ref_wfn), options);
+        RSCFDeriv hessian_computer(std::static_pointer_cast<scf::RHF>(ref_wfn), options);
```
Comment (JonathonMisiewicz) [inline psi4/src/psi4/scfgrad/wrapper.cc:59]:
```suggestion
        RSCFDeriv hessian_computer(std::dynamic_pointer_cast<scf::RHF>(ref_wfn), options);
```

File: psi4/src/psi4/scfgrad/wrapper.cc [hunk 2]
```diff
@@ -49,17 +49,17 @@ SharedMatrix scfgrad(SharedWavefunction ref_wfn, Options &options)
...
         H = hessian_computer.compute_hessian();
     } else {
-        USCFDeriv hessian_computer(std::dynamic_pointer_cast<scf::UHF>(ref_wfn), options);
+        USCFDeriv hessian_computer(std::static_pointer_cast<scf::UHF>(ref_wfn), options);
```
Comment (JonathonMisiewicz) [inline psi4/src/psi4/scfgrad/wrapper.cc:62]:
```suggestion
        USCFDeriv hessian_computer(std::dynamic_pointer_cast<scf::UHF>(ref_wfn), options);
```

**Review by loriab — APPROVED** [review]
lgtm, thanks!

I've tried to imagine scenarios where one would want to compute a SCF deriv on a post-HF wfn, but using the reference_wavefunction or pre-casting seems reasonable.

**Review by zachglick — APPROVED** [review]

**Review by jturney — APPROVED** [review]
