### PR TITLE
VV10: Fixes UKS non-local dispersion

### LINKED ISSUE #962: Strange M05-2X Gradient Behavior
## Description
During the course of one of my projects, where I was attempting to perform very tight optimizations of nonbonded clusters with DFT, I encountered some very strange noise in the DF-M05-2X analytic gradients with Psi4.  The noise actually prevented us from successfully converging several optimizations to `g_convergence interfrag_tight`.

I've attached [this file](https://github.com/psi4/psi4/files/1908011/summary.txt) which contains a variety of gradients, computed using a new-ish version of Psi4 (1.2a1), pre-inversion Psi4 (PSI 4.0.0-beta5) and Q-Chem 4.4, but I'll summarize the results here.

Modern Psi4 (1.2a1):
- Density fitting errors in M05-2X yield gradient noise of around 10^{-6} in analytic gradients vs. direct
- Increasing the grid density from the standard (72, 302) to (150, 434) can result in differences as large as 10^{-3} for DF-M05-2X vs. 5pt FD
- Neither direct- nor DF-M05-2X match either 3- or 5-point numerical gradients, which match each other to < 10^{-7}
- DF-B97/cc-pVDZ analytic vs. 5-point FD grad match to ~10^{-5}, and DF-RHF/cc-pVDZ, direct-RHF/cc-pVDZ, & FD(5pt)-RHF/cc-pVDZ all match to < 10^{-7}

Psi4 Beta5:
- Analytic DF-M05-2X gradients vs 5pt FD exhibit differences as large as 10^{-4}
- Similarly small density fitting error vs direct as in modern Psi4
- DF-RHF analytic grads match 5pt FD nearly perfectly, density fitting differences of < 10^{-5}

vs. Q-Chem 4.4 (apples-to-apples comparisons):
- Psi4 1.2a1 analytic direct-M05-2X w/ dense grids, analytic direct-RHF both agree w/ Q-Chem to 10^{-5}
- Psi4 Beta5 analytic direct-M05-2X w/ dense grids matches to ~10^{-5}, with direct-RHF matching to 10^{-7}

I'm unsure if this is an issue in the FINDIF code which may be fortuitously resolved by #884 or more of the same strange behavior noted by @CDSherrill in #867, but we thought it strange enough to want to bring it to the greater community's attention.

### LINKED ISSUE #982: Enable VV10 for UHF

### PR DESCRIPTION
**Pull request by dgasmith**
## Description
Patch up VV10 UKS dispersion. This had been a nagging issue for awhile now, but it turns out the only real issue is that I forgot to add the VV10 energy to the total SCF energy. I had originally started blaming the Fock term as the VV10 energy was spot on and subsequently starting playing with those values. Quite the blooper on my part:

```
(p4dev) daniel:~/Gits/psi4ds/tests/dft-bench-ionization (vv10_uks)$ python ../../psi4/run_psi4.py --inplace input.dat
	VSXC: Psi4 vs. Q-Chem.............................................PASSED
	VV10: Psi4 vs. Q-Chem.............................................PASSED
	B97M-V: Psi4 vs. Q-Chem...........................................PASSED
	LC-VV10: Psi4 vs. Q-Chem..........................................PASSED
	wB97M-V: Psi4 vs. Q-Chem..........................................PASSED
	wB97X-V: Psi4 vs. Q-Chem..........................................PASSED
```

This also fixes a small bug in meta-GGA UKS gradients from the original implementation.

Fixes #982 and fixes #962.

## Status
- [x] Ready for review
- [x] Ready for merge

### CODE REVIEW

File: psi4/src/psi4/libfock/v.cc [hunk 1]
```diff
@@ -2468,18 +2468,17 @@ SharedMatrix UV::compute_gradient() {
...
             v_tau_s[0] = v_tau_a;
             v_tau_s[1] = v_tau_b;
 
             for (int s = 0; s < 2; s++) {
-                //                double** Dp = Ds[s];
                 double* v_tau = v_tau_s[s];
                 for (int i = 0; i < 3; i++) {
                     double*** phi_j = phi_ij[i];
-                    C_DGEMM('N', 'N', npoints, nlocal, nlocal, 1.0, phi_i[i][0], max_functions, Dap[0], max_functions,
+                    C_DGEMM('N', 'N', npoints, nlocal, nlocal, 1.0, phi_i[i][0], max_functions, Ds[s][0], max_functions,
```
Comment (susilehtola) [inline psi4/src/psi4/libfock/v.cc]: :+1:
